### PR TITLE
Fix: memory leaks

### LINKED ISSUE #717: Fix all memory leaks in compiler

### PR DESCRIPTION
**Pull request by LindonAliu**
Closes #717

### CODE REVIEW

File: lib/Sema/ModuleWalker.cpp [hunk 1]
```diff
@@ -127,7 +129,8 @@ class ModuleWalker : public glu::ast::ASTWalker<ModuleWalker, void> {
     {
         if (_skippingCurrentFunction)
             return;
-        _scopeTable = new (_scopeTableAllocator) ScopeTable(_scopeTable, node);
+        _scopeTable = new (_scopeTableAllocator.Allocate())
+            ScopeTable(_scopeTable, node);
```
Comment (Snowy1803) [inline lib/Sema/ModuleWalker.cpp]: Scope Tables for FunctionDecl and CompoundStmt are local — they probably shouldn't be allocated on the importmanager's scope table allocator because they are not used outside of ModuleWalker. Otherwise, those scope tables are kept for the whole lifetime of the compiler even when they are only used when applying sema on a single function. You could use a separate allocator within the ModuleWalker.

**Review by Snowy1803 — DISMISSED** [review]
