### PR TITLE
Fix: FieldDecl in CSWalker

### LINKED ISSUE #545: Fix FieldDecl's default values not being resolved by CSWalker
Resolve XFAIL in `test/functional/run/struct.glu`

### LINKED ISSUE #577: Fix StructInitializerExpr not resolving its arguments

### PR DESCRIPTION
**Pull request by LindonAliu**
fix #545 
Fix #577

### CODE REVIEW

File: lib/Sema/CSWalker.cpp [hunk 1]
```diff
@@ -325,7 +325,18 @@ class LocalCSWalker : public glu::ast::ASTWalker<LocalCSWalker, void> {
...
+    {
+        auto *structType = node->getType();
+
+        if (!structType)
+            return;
+
+        auto constraint = Constraint::createStructInitialiser(
+            _cs.getAllocator(), structType, node
+        );
+        _cs.addConstraint(constraint);
```
Comment (Snowy1803) [inline lib/Sema/CSWalker.cpp:338]: the type cannot possibly be null
```suggestion
        auto constraint = Constraint::createStructInitialiser(
            _cs.getAllocator(), structType, node->getType()
        );
        _cs.addConstraint(constraint);
```

File: lib/Sema/CSWalker.cpp [hunk 2]
```diff
@@ -529,6 +540,15 @@ class GlobalCSWalker : public glu::ast::ASTWalker<GlobalCSWalker, void> {
         }
     }
 
+    void postVisitFieldDecl(glu::ast::FieldDecl *node)
+    {
+        _scopeTable->insertItem(node->getName(), node, node->getVisibility());
```
Comment (Snowy1803) [inline lib/Sema/CSWalker.cpp:545]: the field shouldn't be added to the global scope table
