### PR TITLE
Fix: `-O` option

### LINKED ISSUE #603: Add `-O` CLI option for enabling default LLVM optimizations
- `-O` doesn't work by itself
- optimization not done when using `--print-llvm-ir`

### PR DESCRIPTION
**Pull request by Snowy1803**
Closes #603

### CODE REVIEW

File: tools/gluc/sources/CompilerDriver.cpp [hunk 1]
```diff
@@ -115,12 +124,43 @@ bool CompilerDriver::parseCommandLine(int argc, char **argv)
...
+        optLevel = 3;
+        optCount++;
+    }
+
+    // Validate that only one optimization level is specified
+    if (optCount > 1) {
+        llvm::errs() << "Error: Multiple optimization levels specified\n";
+        return false;
+    }
+
```
Comment (LindonAliu) [inline tools/gluc/sources/CompilerDriver.cpp:157]: create a function for this

**Review by LindonAliu — DISMISSED** [review]

**Review by LindonAliu — DISMISSED** [review]
nice!

**Review by LindonAliu — APPROVED** [review]
